<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PolicyItemFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicyItemFieldsRepository extends EntityRepository
{
    public function findAllFieldsByType($type)
    {
        return $this->queryAllFieldsByType($type)
            ->getQuery()
            ->getResult();
    }

    public function queryAllFieldsByType($type)
    {
        return $this->createQueryBuilder('f')
            ->where('f.type = :type')
            ->setParameter('type', $type);
    }
}
