##  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 #
 #  Use of this source code is governed by a BSD-style license that can
 #  be found in the License.html file in the root of the source tree.
 ##

#! /bin/sh

#-----------------------------------------------------------------------
# $1=OS, $2=Platform
Release_CLI()
{
#-----------------------------------------------------------------------
# Clean up
test -e MediaConch_CLI_$1_$2.tar     && rm    MediaConch_CLI_$1_$2.tar
test -e MediaConch_CLI_$1_$2.tar.bz2 && rm    MediaConch_CLI_$1_$2.tar.bz2
test -d MediaConch_CLI_$1_$2         && rm -r MediaConch_CLI_$1_$2
mkdir   MediaConch_CLI_$1_$2

#-----------------------------------------------------------------------
# Copying : Exe
cp ../Project/GNU/CLI/mediaconch MediaConch_CLI_$1_$2/mediaconch
cd MediaConch_CLI_$1_$2
strip mediaconch
cd ..

#-----------------------------------------------------------------------
# Copying : Information file
cp ../License.html MediaConch_CLI_$1_$2/
cp ../History_CLI.txt MediaConch_CLI_$1_$2/History.txt
cp ReadMe_CLI_$1.txt MediaConch_CLI_$1_$2/ReadMe.txt

#-----------------------------------------------------------------------
# Copying : Information file
mkdir -p MediaConch_CLI_$1_$2/Contrib
cp ../Contrib/CLI_Help.doc MediaConch_CLI_$1_$2/Contrib/

#-----------------------------------------------------------------------
# Compressing Archive
tar jchf MediaConch_CLI_$1_$2.tar.bz2 MediaConch_CLI_$1_$2

#-----------------------------------------------------------------------
# Clean up
#if "%1"=="SkipCleanUp" goto SkipCleanUp
#rm -r MediaConch_CLI_$1_$2
#:SkipCleanUp
}

